# APPLICATION
spring.application.name=school-manager-api
server.port=8080
server.servlet.context-path=/api

# BASE DE DONNÉES MASTER
spring.datasource.url=jdbc:postgresql://localhost:5432/dbgestioneducation
spring.datasource.username=postgres
spring.datasource.password=11017762
spring.datasource.driver-class-name=org.postgresql.Driver

# POOL HIKARICP
spring.datasource.hikari.pool-name=MasterPool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# TENANT CONFIG
app.tenant.header-name=X-Tenant-ID
app.tenant.db-prefix=dbgestioneducation_tenant_
app.tenant.db-host=localhost
app.tenant.db-port=5432
app.tenant.db-user=postgres
app.tenant.db-password=11017762

# JWT
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=method

# LOGGING
logging.level.com.edusecure=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level [tenant:%X{tenantId}] %logger{20} - %msg%n
